# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 tomyimkc
"""Read/write substrate for the OKF wiki — the agent's long-term semantic memory.

Canonical entity pages live under wiki/<pageType>/ (generated by tools/wiki_sync.py
from data/*.json). The agent never overwrites those; it writes to two agent-owned
tiers: a memory tier (consolidated knowledge, agent/memory/wiki/) and a draft tier
(librarian proposals, wiki/drafts/). EVERY write is gated by the provenance
verifiers, so the agent can grow its own knowledge base but can never commit a
schema-invalid page or a lineage merge. The MCP layer adds the audit/approval gate.
"""

from __future__ import annotations

import re

from datetime import datetime, timezone
from pathlib import Path

from agent.config import DISPUTES_DIR as _DISPUTES_DIR
from agent.config import WIKI_DIR, WIKI_DRAFT_DIR, WIKI_MEMORY_DIR
from agent.verifiers import provenance_faithful
from okf import frontmatter, graph as okf_graph, page as okf_page, schema

# Module-level dirs (tests may monkeypatch these to redirect to a tmp tree).
CANONICAL_DIR = WIKI_DIR
MEMORY_DIR = WIKI_MEMORY_DIR
DRAFT_DIR = WIKI_DRAFT_DIR
DISPUTES_DIR = _DISPUTES_DIR


def _tier_dir(tier: str) -> "Path | None":
    return {"memory": MEMORY_DIR, "draft": DRAFT_DIR}.get(tier)


def _read_roots() -> "list":
    return [d for d in (CANONICAL_DIR, MEMORY_DIR, DRAFT_DIR) if Path(d).exists()]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_all_pages() -> "list":
    """All OKF pages across canonical, memory, and draft tiers."""
    return okf_page.load_pages(*_read_roots())


def belief_graph_pages() -> "list":
    """Pages for belief-graph queries (belief / counterfactual / retract / revise):
    the store tiers PLUS the hand-curated dispute pages, which carry the
    ``derivesFrom`` lineage edges. The store tiers win on any id collision (the
    canonical record outranks a dispute note that reuses its id), so this never
    shadows a generated page — it only *adds* the dispute lineage the store omits.
    """
    pages = load_all_pages()
    seen = {p.id for p in pages}
    if Path(DISPUTES_DIR).exists():
        for page in okf_page.load_pages(DISPUTES_DIR):
            if page.id not in seen:
                pages.append(page)
                seen.add(page.id)
    return pages


def index_by_id() -> dict:
    """id -> Page; canonical wiki wins over memory/draft on conflict."""
    index: dict = {}
    for page in load_all_pages():
        index.setdefault(page.id, page)
    return index


def read_page(page_id: str):
    return index_by_id().get(page_id)


def gate(meta: dict, body: str) -> "tuple":
    """Return (ok, reasons). Schema-valid frontmatter + no forbidden attribution +
    no self-inconsistent lineage merge. The hard gate on every agent write."""
    reasons: list[str] = list(schema.validate_meta(meta))

    pf = provenance_faithful()(body, None, {})
    if not pf["passed"]:
        reasons += pf["reasons"]

    author = meta.get("attributedAuthor")
    forbidden = {str(a).lower() for a in schema.as_list(meta.get("doNotAttributeTo"))}
    if author and str(author).lower() in forbidden:
        reasons.append(f"lineage-merge: attributedAuthor '{author}' is in doNotAttributeTo")

    return (not reasons, reasons)


def upsert(page_id: str, *, meta: "dict | None" = None, body: str = "", tier: str = "memory") -> dict:
    """Create or update an agent-owned page, gated by provenance verifiers.

    Merges new frontmatter onto any existing page, stamps id/pageType/updated/
    revisions, validates, and writes only if the gate passes. Returns a structured
    result (never raises on a gate failure).
    """
    target_dir = _tier_dir(tier)
    if target_dir is None:
        return {"ok": False, "error": f"unknown tier '{tier}' (allowed: memory, draft)"}

    # Sanitize the user-provided page_id at the source: it becomes a filename, so reject
    # anything that is not a flat slug (no path separators, no traversal). This guard plus
    # the resolve()/relative_to()/parent checks below make traversal impossible at runtime;
    # CodeQL's path-injection query only models const-compare barriers, so it still reports
    # the sinks below as a known false positive on this validated input.
    if not re.fullmatch(r"[A-Za-z0-9._-]+", page_id or "") or page_id in (".", ".."):
        return {"ok": False, "error": f"invalid page id '{page_id}'", "id": page_id}

    existing = read_page(page_id)
    merged = dict(existing.meta) if existing else {}
    merged.update(meta or {})
    merged["id"] = page_id
    merged.setdefault("pageType", "memory")
    merged["updated"] = _now()
    merged["revisions"] = int(merged.get("revisions") or 0) + 1
    new_body = body if body else (existing.body if existing else "")

    ok, reasons = gate(merged, new_body)
    if not ok:
        return {"ok": False, "rejected": True, "reasons": reasons, "id": page_id}

    base_dir = Path(target_dir).resolve()
    path = (base_dir / f"{page_id}.md").resolve()
    # Sanitize user-provided page_id: reject any value that escapes the tier directory.
    try:
        path.relative_to(base_dir)
    except ValueError:
        return {"ok": False, "error": f"invalid page id '{page_id}'", "id": page_id}
    if path.parent != base_dir:
        return {"ok": False, "error": f"invalid page id '{page_id}'", "id": page_id}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(frontmatter.serialize(merged, new_body), encoding="utf-8")
    base = Path(CANONICAL_DIR).parent
    rel = path.relative_to(base) if path.is_relative_to(base) else path
    return {"ok": True, "id": page_id, "path": str(rel), "tier": tier, "revisions": merged["revisions"]}


def search(query: str, *, top_k: int = 8) -> "list":
    """Lightweight keyword search over wiki pages (id/body), for plan-time recall."""
    tokens = {t for t in query.lower().split() if len(t) > 2}
    scored: list = []
    for page in load_all_pages():
        hay = f"{page.id} {page.body}".lower()
        score = sum(1 for t in tokens if t in hay)
        if score:
            scored.append((score, page))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [p for _, p in scored[:top_k]]


def contradictions() -> dict:
    """Structural contradiction ledger over the whole current wiki (all tiers)."""
    from okf import linker

    graph = okf_graph.build(load_all_pages())
    return okf_graph.contradiction_ledger(graph, dnm_by_tradition=linker.load_dnm_by_tradition())
